### PR TITLE
Handle insufficient funds

### LINKED ISSUE #13: Incorrect handling of transactions in case of insufficient funds
If a validator has no enough funds to handle transaction the bridge is trying to send transaction, fails and updating the database:

```
Found 1 Deposits on Home Network
Error! { code: -32010,
  message: 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 2314865000000000 and got: 0.' }
1 '# processing deposit' '0xa85bb9dca943978bff7054db8172cc7c382cb321364e3b7fd3f137d30bb51983' undefined
writing db deposits 91
```

It leads to necessity to stop the bridge, roll back the changes in database manually and start the bride again after the validator balance refill.

So, in order to handle 'insufficient funds' issue properly the bridge should:
1. check balance of validator on Home and Foreign side as soon as the corresponding event (`Deposit`, `CollectedSignaturs` or `Withdraw`) to relay transaction is received
2. only if the balance is positive, relay transaction
3. otherwise the bridge must stop operations in the corresponding direction until the validator balance is refilled. **No database updates must be done** for the corresponding event type.

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #13.

If some transaction fails because of insufficient funds, close the connection and don't wait for the balance of the validator to change.

To avoid weird circumstances, we added a `prefetch(1)` that means that only one message will be processed at the same time. This shouldn't affect the performance significantly since most of the processing is locked by the nonce anyway. In fact, this may render the lock unnecessary, but since it won't hurt either we left it. We should consider removing it, though.

### CODE REVIEW

File: src/sender.js [hunk 1]
```diff
@@ -121,6 +125,11 @@ async function main({ msg, ackMsg, nackMsg, sendToQueue }) {
       await sendToQueue(failedTx)
     }
     ackMsg(msg)
+
+    if (insufficientFunds) {
+      channel.close()
+      waitForFunds(web3Instance, VALIDATOR_ADDRESS, initialize)
```
Comment (patitonar) [inline src/sender.js]: I think it would be useful to add 2 logs. One with a message that it will stop processing jobs because of the funds, and a second log with a message that the validator have funds again and it will start processing jobs

Comment (patitonar) [inline src/sender.js]: I think it would be useful to add 2 logs. One with a message that it will stop processing jobs because of the funds, and a second log with a message that the validator have funds again and it will start processing jobs

Comment (fvictorio) [reply src/sender.js]: Added.

File: src/utils/utils.js [hunk 2]
```diff
@@ -16,7 +18,27 @@ function checkHTTPS(ALLOW_HTTP) {
   }
 }
 
+async function waitForFunds(web3, address, cb) {
+  const balance = web3.utils.toBN(await web3.eth.getBalance(address))
+
+  promiseRetry(
+    async retry => {
+      const newBalance = web3.utils.toBN(await web3.eth.getBalance(address))
+      if (newBalance.eq(balance)) {
```
Comment (akolotov) [inline src/utils/utils.js]: you are looking for any difference in balances. Does it make sense to resume only if balance is enough to send particular transaction (gas usage * gas price)?

File: src/sender.js [hunk 3]
```diff
@@ -101,7 +107,10 @@ async function main({ msg, ackMsg, nackMsg, sendToQueue }) {
         console.error(`Tx Failed for event Tx ${job.transactionReference}`)
         failedTx.push(job)
 
-        if (
+        if (e.message.includes('Insufficient funds')) {
+          console.error('Insufficient funds')
```
Comment (akolotov) [inline src/sender.js]: Will the similar message be logged anyway in the line 106? Will we have duplicated lines in the logs?

Comment (fvictorio) [reply src/sender.js]: You are right. We can just remove this comment, or make it more clear. What about something like:

```Insufficient funds: ${currentBalance}. Stop consuming messages until the balance is ${minimumBalance}.```

File: src/utils/utils.js (hunk 2 above)
Comment (fvictorio) [reply src/utils/utils.js]: Fixed, thanks.

File: src/sender.js [hunk 4]
```diff
@@ -101,7 +110,16 @@ async function main({ msg, ackMsg, nackMsg, sendToQueue }) {
         console.error(`Tx Failed for event Tx ${job.transactionReference}`)
         failedTx.push(job)
 
-        if (
+        if (e.message.includes('Insufficient funds')) {
+          insufficientFunds = true
+          const currentBalance = await web3Instance.eth.getBalance(VALIDATOR_ADDRESS)
+          minimumBalance = toBN(job.gasEstimate)
+            .add(toBN(200000))
```
Comment (akolotov) [inline src/sender.js]: Could you clarify why you added 200_000 of gas? Does it make sense to add 20%?
Whatever the value you are using, let use a constant and provide a comment to expose its meaning. Thanks

Comment (fvictorio) [reply src/sender.js]: Oh, yes, sorry. That is the amount that is being added some lines above to the estimated gas. But I totally agree that it should be in a constant. Maybe something like `EXTRA_GAS = 200000`? Or we could use a percentage.

Comment (akolotov) [reply src/sender.js]: I would prefer to use a percentage. Otherwise for transactions which requires less than 100 thousands the gas parameter will have the value 3 times more than required.

Comment (fvictorio) [reply src/sender.js]: Done. I added a constant for the extra percentage and a function that applies this increase.

**Comment by rstormsf** [comment]
I always  add a little more gas, cause estimateGas can be wrong a little bit depending which  node is executing the  tx: geth or parity.

**Comment by fvictorio** [comment]
@rstormsf Do you think that adding a 5% to the estimated gas should be OK?

**Comment by rstormsf** [comment]
@fvictorio lets add 25% to the  gas.

**Comment by fvictorio** [comment]
@rstormsf Done.
